### ISSUE TITLE
Cambio en la home

### ISSUE THREAD

**Issue by gonzaggb** [gonzaggb/grupo_2_focalGlow#2]
@Pablito-1988 Creo que podriamos agregar el banner en version mobile, ya que es importante que el que accede desde un telefono sepa de todas las posibilidades que hay en el sitio:
para ello en 

.banner{
    flex-direction: row;
    line-height: 12px;
    font-size: 9px;
}
a cada banner-box definirle 30% de width y creo que con eso queda.
adjunto imagen de como se ve al 100%
![image](https://user-images.githubusercontent.com/81274078/117897294-de57c800-b298-11eb-935c-a63c99df99b7.png)

@martinianol

**Comment by Pablito-1988** [comment]
me gusta, si me dan el ok lo cambio
